description: >
  Default base executor.
parameters:
  image:
    type: string
    default: cimg/base:current
  docker_layer_caching:
    type: boolean
    default: true
  resource_class:
    type: string
    default: medium

machine:
  image: <<parameters.image>>
  docker_layer_caching: <<parameters.docker_layer_caching>>

resource_class: <<parameters.resource_class>>
